name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - uses: aarnott/nbgv@v0.4.0
      with:
        setAllVars: true
    - run: echo "NBGV_SemVer2 $NBGV_SemVer2"
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/BasicService/BasicService.sln
    - name: Build
      run: dotnet build ./src/BasicService/BasicService.sln -c Release 
    - name: Test
      run: dotnet test ./src/BasicService/BasicService.sln
