# This is a basic workflow to help you get started with Actions

name: Build release

# Controls when the action will run. 
on:
  push:
    tags:
      - "v*"
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Build:
    runs-on: ubuntu-20.04

    env:
      COMMIT_REF: $(git rev-parse --short "$GITHUB_SHA")

    steps:
      - uses: actions/checkout@v2

      - name: Get the branch
        id: get_branch
        run: echo ::set-output name=BRANCH::${GITHUB_REF/refs\/heads\//}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
            
      - name: Create Resource Group
        run: |
          az group create -g "${{ secrets.RESOURCE_GROUP }}" -l "West US"

      - name: Deploy Azure Resource Manager (ARM) Template
        uses: azure/arm-deploy@v1
        id: deploy
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
          template: ./infrasetup/main.bicep
          deploymentMode: Incremental
            
      - name: Build image with ACR
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az acr build --registry ${{ steps.deploy.outputs.registryNameOutput }} --image featherservicetest_release:${{ steps.get_version.outputs.VERSION }} ./src/BasicService/
            
      - name: pushover-actions
        if: always()
        uses: umahmood/pushover-actions@main
        env:
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
        with:
          status: ${{ job.status }}
          title: 'Feather new release build completed with tag ${{ steps.get_version.outputs.VERSION }}' 
          message: ${{ job.status }}
            
        
